apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "api.fullname" . }}
  labels:
    app: {{ template "api.name" . }}
    chart: {{ template "api.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        release: "{{ .Release.Name }}"
        role: api
        app: {{ template "api.name" . }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end}}
      {{- end}}
      containers:
      - image: {{ .Values.image.repository }}
        name: {{ .Release.Name }}
        ports:
        - containerPort: 80
        env:
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}
              key: REDIS_URL
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}
              key: KAFKA_BOOTSTRAP_SERVERS
