apiVersion: v1
kind: Service
metadata:
  name: {{ template "api.fullname" . }}
  labels:
    app: {{ template "api.name" . }}
    chart: {{ template "api.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: koralium
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ template "api.name" . }}
    release: "{{ .Release.Name }}"