dependencies:
  - name: dashboard
    version: 0.1.0
    condition: dashboard.enabled
  - name: api
    version: 0.1.0
    condition: api.enabled
  - name: worker
    version: 0.1.0
    condition: worker.enabled