api:
  image:
    repository: koralium/koralium-api
    pullSecrets:
    - koralium
  service:
    type: ClusterIP
  ingress:
    enabled: true
    host: xip.io

worker:
  image:
    repository: koralium/koralium-worker
    pullSecrets:
    - koralium
  replicas: 1

# Redis values
redis:
  url: ""

kafka:
  boostrapservers: ""