apiVersion: v1
kind: Service
metadata:
  name: {{ template "koralium.fullname" . }}-api
  labels:
    app: {{ template "koralium.name" . }}
    chart: {{ template "koralium.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - name: koralium
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ template "koralium.name" . }}
    release: "{{ .Release.Name }}"