apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "koralium.name" . }}
    chart: {{ template "koralium.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  REDIS_URL: {{ .Values.redis.url }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.boostrapservers }}
  {{- if .Values.dashboard.apiUrlOverride -}}
  API_URL: "{{ .Values.dashboard.apiUrlOverride }}"
  {{- end -}}

