apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "koraliumsqlserver.name" . }}
    chart: {{ template "koraliumsqlserver.chart" . }}
    release: "{{ .Release.Name }}"
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        release: "{{ .Release.Name }}"
        role: producer
        app: {{ template "koraliumsqlserver.name" . }}
    spec:
      containers:
      - image: koralium/sqlserversource
        name: {{ .Release.Name }}
        resources: {}
        env:
        - name: DB_DATA_SOURCE
          value: {{ .Values.database.datasource }}
        - name: DB_DATABASE
          value: {{ .Values.database.name }}
        - name: DB_USERNAME
          value: {{ .Values.database.username }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "koraliumsqlserver.name" . }}
              key: sqlserver-password
        - name: DB_TABLE
          value: {{ .Values.database.table }}