apiVersion: v1
kind: Secret
metadata:
  name: {{ template "koraliumsqlserver.name" . }}
  labels:
    app: {{ template "koraliumsqlserver.name" .}}
    chart: {{ template "koraliumsqlserver.chart" . }}
    release: "{{ .Release.Name }}"
type: Opaque
data:
  sqlserver-password: {{ .Values.database.password }}